FROM python:3.11-bullseye

# Install Python packages
RUN pip install \
    flask

COPY website /website

WORKDIR /website
ENTRYPOINT [ "/usr/local/bin/flask", "--app", "hello", "run", "--host=0.0.0.0" ]