FROM gornet/voluseg:1.0.0

RUN pip install psutil

COPY worker /worker

WORKDIR /worker
ENTRYPOINT [ "/usr/local/bin/celery", "-A", "worker", "worker", "-P", "prefork", "-c", "1", "--loglevel=info", "-Q", "tasks" ]
