FROM python:3.11-bullseye

# Install Python packages
RUN pip install \
    flask

COPY hello-flask /hello-flask

WORKDIR /hello-flask
ENTRYPOINT [ "/usr/local/bin/flask", "--app", "app", "run", "--host=0.0.0.0" ]