apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7.4.1
        args:
        - "--tls-port"
        - "6379"
        - "--port"
        - "6380"
        - "--tls-cert-file"
        - "/etc/redis/tls/redis.crt"
        - "--tls-key-file" 
        - "/etc/redis/tls/redis.key"
        - "--tls-ca-cert-file"
        - "/etc/redis/tls/ca.crt"
        - "--tls-auth-clients"
        - "no"
        ports:
        - containerPort: 6379
        - containerPort: 6380
        volumeMounts:
        - name: redis-tls
          mountPath: /etc/redis/tls
          readOnly: true
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
      volumes:
      - name: redis-tls
        secret:
          secretName: celery-redis-tls-secret
---
apiVersion: v1
kind: Service
metadata:
  name: redis-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis-tls-service
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6380
      targetPort: 6380
