apiVersion: apps/v1
kind: Deployment
metadata:
  name: voluseg-worker
  labels:
    app: voluseg-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voluseg-worker
  template:
    metadata:
      labels:
        app: voluseg-worker
    spec:
      imagePullSecrets:
      - name: regcred
      nodeSelector:
        "kops.k8s.io/instancegroup": "spotgroup"
      tolerations:
      - key: "compute"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      containers:
      - name: voluseg-worker
        image: gornet/voluseg-worker:0.0.25
        env:
        - name: S3_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-s3-secret
              key: S3_ACCESS_KEY_ID
        - name: S3_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-s3-secret
              key: S3_SECRET_ACCESS_KEY
        - name: REDIS_URL
          value: "redis://redis-service:6380/0"
        - name: RABBITMQ_URL
          value: "amqp://guest:guest@rabbitmq-service:5672/celery_vhost"
        volumeMounts:
        - name: temporary-volume
          mountPath: /data
        resources:
          requests:
            memory: 60Gi
      volumes:
      - name: redis-tls
        secret:
          secretName: celery-redis-tls-secret
      - name: temporary-volume
        ephemeral:
          volumeClaimTemplate:
            spec:
              accessModes: [ "ReadWriteOnce" ]
              resources:
                requests:
                  storage: 200Gi
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: voluseg-worker-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: voluseg-worker
    kind: Deployment
  pollingInterval: 30
  cooldownPeriod: 10800
  maxReplicaCount: 20
  minReplicaCount: 0
  triggers:
    - type: redis
      metadata:
        address: "redis-service.default.svc.cluster.local:6380"
        databaseIndex: "0"
        listName: "tasks"
        activationListLength: "1"