name: Kubernetes CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile.webserver'
      - 'website/**'
      - '.github/workflows/deploy.yaml'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-push:
    name: Build and Push Container
    runs-on: ubuntu-latest
    strategy:
      matrix:
        worker: [webserver]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker Metadata
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/cell-segmentation-${{ matrix.worker }}
          tags: ${{ github.sha }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and Push Worker
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.${{ matrix.worker }}
          push: true
          tags: |
            ${{ steps.docker_meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha
  deploy:
    name: Deploy to Kubernetes
    needs: build-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: azure/setup-kubectl@v3
      - uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
      - uses: azure/k8s-deploy@v4
        with:
          manifests: |
            deploy/webserver-deployment.yaml
          images: |
            ghcr.io/jgornet/cell-segmentation/cell-segmentation-webserver:${{ github.sha }}
          pull-images: false # don't try to annotate deployments
          namespace: default